# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1806, 1204)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(315, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(315, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.dateAndTimeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.dateAndTimeLabel.setObjectName("dateAndTimeLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dateAndTimeLabel)
        self.dateAndTimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateAndTimeDateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateAndTimeDateTimeEdit.setDate(QtCore.QDate(2020, 6, 1))
        self.dateAndTimeDateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateAndTimeDateTimeEdit.setCalendarPopup(True)
        self.dateAndTimeDateTimeEdit.setObjectName("dateAndTimeDateTimeEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateAndTimeDateTimeEdit)
        self.projectNameLabel = QtWidgets.QLabel(self.groupBox_3)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.projectNameLabel)
        self.projectNameLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.projectNameLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.projectNameLineEdit)
        self.gun1TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun1TotalShotsLabel.setObjectName("gun1TotalShotsLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel)
        self.gun1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.gun1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.gun1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun1TotalShotsSpinBox.setMaximum(10000000)
        self.gun1TotalShotsSpinBox.setObjectName("gun1TotalShotsSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gun1TotalShotsSpinBox)
        self.gun2TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun2TotalShotsLabel.setObjectName("gun2TotalShotsLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel)
        self.gun2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun2TotalShotsSpinBox.setMaximum(10000000)
        self.gun2TotalShotsSpinBox.setObjectName("gun2TotalShotsSpinBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gun2TotalShotsSpinBox)
        self.gun3TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun3TotalShotsLabel.setObjectName("gun3TotalShotsLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel)
        self.gun3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun3TotalShotsSpinBox.setMaximum(10000000)
        self.gun3TotalShotsSpinBox.setObjectName("gun3TotalShotsSpinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gun3TotalShotsSpinBox)
        self.gun4TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun4TotalShotsLabel.setObjectName("gun4TotalShotsLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel)
        self.gun4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun4TotalShotsSpinBox.setMaximum(10000000)
        self.gun4TotalShotsSpinBox.setObjectName("gun4TotalShotsSpinBox")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gun4TotalShotsSpinBox)
        self.gun5TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun5TotalShotsLabel.setObjectName("gun5TotalShotsLabel")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel)
        self.gun5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun5TotalShotsSpinBox.setMaximum(10000000)
        self.gun5TotalShotsSpinBox.setObjectName("gun5TotalShotsSpinBox")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gun5TotalShotsSpinBox)
        self.gun6TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gun6TotalShotsLabel.setObjectName("gun6TotalShotsLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel)
        self.gun6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.gun6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun6TotalShotsSpinBox.setMaximum(10000000)
        self.gun6TotalShotsSpinBox.setObjectName("gun6TotalShotsSpinBox")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.gun6TotalShotsSpinBox)
        self.mSGTotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.mSGTotalShotsLabel.setObjectName("mSGTotalShotsLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel)
        self.mSGTotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.mSGTotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.mSGTotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mSGTotalShotsSpinBox.setMaximum(10000000)
        self.mSGTotalShotsSpinBox.setObjectName("mSGTotalShotsSpinBox")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.mSGTotalShotsSpinBox)
        self.commentsLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.commentsLabel_2.setObjectName("commentsLabel_2")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.commentsLabel_2)
        self.comments_txt = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments_txt.sizePolicy().hasHeightForWidth())
        self.comments_txt.setSizePolicy(sizePolicy)
        self.comments_txt.setMinimumSize(QtCore.QSize(150, 100))
        self.comments_txt.setMaximumSize(QtCore.QSize(100, 100))
        self.comments_txt.setUndoRedoEnabled(True)
        self.comments_txt.setReadOnly(False)
        self.comments_txt.setObjectName("comments_txt")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comments_txt)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setObjectName("formLayout_4")
        self.gun1TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun1TotalShotsLabel_2.setObjectName("gun1TotalShotsLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_2)
        self.airline1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airline1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.airline1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.airline1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline1TotalShotsSpinBox.setMaximum(10000000)
        self.airline1TotalShotsSpinBox.setObjectName("airline1TotalShotsSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.airline1TotalShotsSpinBox)
        self.airline1TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline1TypeLabel.setObjectName("airline1TypeLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.airline1TypeLabel)
        self.gun2TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun2TotalShotsLabel_2.setObjectName("gun2TotalShotsLabel_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_2)
        self.airline2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline2TotalShotsSpinBox.setMaximum(10000000)
        self.airline2TotalShotsSpinBox.setObjectName("airline2TotalShotsSpinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.airline2TotalShotsSpinBox)
        self.airline2TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline2TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline2TypeComboBox.setObjectName("airline2TypeComboBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.airline2TypeComboBox)
        self.gun3TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun3TotalShotsLabel_2.setObjectName("gun3TotalShotsLabel_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_2)
        self.airline3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline3TotalShotsSpinBox.setMaximum(10000000)
        self.airline3TotalShotsSpinBox.setObjectName("airline3TotalShotsSpinBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.airline3TotalShotsSpinBox)
        self.airline3TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline3TypeLabel.setObjectName("airline3TypeLabel")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.airline3TypeLabel)
        self.gun4TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun4TotalShotsLabel_2.setObjectName("gun4TotalShotsLabel_2")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_2)
        self.airline4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline4TotalShotsSpinBox.setMaximum(10000000)
        self.airline4TotalShotsSpinBox.setObjectName("airline4TotalShotsSpinBox")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.airline4TotalShotsSpinBox)
        self.airline4TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline4TypeLabel.setObjectName("airline4TypeLabel")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.airline4TypeLabel)
        self.airline4TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline4TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline4TypeComboBox.setObjectName("airline4TypeComboBox")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.airline4TypeComboBox)
        self.gun5TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun5TotalShotsLabel_2.setObjectName("gun5TotalShotsLabel_2")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_2)
        self.airline5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline5TotalShotsSpinBox.setMaximum(10000000)
        self.airline5TotalShotsSpinBox.setObjectName("airline5TotalShotsSpinBox")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.airline5TotalShotsSpinBox)
        self.airline5TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline5TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline5TypeComboBox.setObjectName("airline5TypeComboBox")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.airline5TypeComboBox)
        self.gun6TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun6TotalShotsLabel_2.setObjectName("gun6TotalShotsLabel_2")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_2)
        self.airline6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline6TotalShotsSpinBox.setMaximum(10000000)
        self.airline6TotalShotsSpinBox.setObjectName("airline6TotalShotsSpinBox")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.airline6TotalShotsSpinBox)
        self.airline6TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline6TypeLabel.setObjectName("airline6TypeLabel")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.airline6TypeLabel)
        self.airline6TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline6TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline6TypeComboBox.setObjectName("airline6TypeComboBox")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.airline6TypeComboBox)
        self.mSGTotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.mSGTotalShotsLabel_2.setObjectName("mSGTotalShotsLabel_2")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_2)
        self.mSG_airline_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.mSG_airline_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.mSG_airline_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mSG_airline_TotalShotsSpinBox.setMaximum(10000000)
        self.mSG_airline_TotalShotsSpinBox.setObjectName("mSG_airline_TotalShotsSpinBox")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.mSG_airline_TotalShotsSpinBox)
        self.airlineForMSGLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airlineForMSGLabel.setObjectName("airlineForMSGLabel")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.airlineForMSGLabel)
        self.airlineForMSGComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airlineForMSGComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airlineForMSGComboBox.setObjectName("airlineForMSGComboBox")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.airlineForMSGComboBox)
        self.airline3TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline3TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline3TypeComboBox.setObjectName("airline3TypeComboBox")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.airline3TypeComboBox)
        self.airline1TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline1TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline1TypeComboBox.setObjectName("airline1TypeComboBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.airline1TypeComboBox)
        self.airline5TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline5TypeLabel.setObjectName("airline5TypeLabel")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.airline5TypeLabel)
        self.airline2TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline2TypeLabel.setObjectName("airline2TypeLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.airline2TypeLabel)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_5.setObjectName("formLayout_5")
        self.gun1TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun1TotalShotsLabel_3.setObjectName("gun1TotalShotsLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_3)
        self.tb1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.tb1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.tb1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb1TotalShotsSpinBox.setMaximum(10000000)
        self.tb1TotalShotsSpinBox.setObjectName("tb1TotalShotsSpinBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tb1TotalShotsSpinBox)
        self.gun2TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun2TotalShotsLabel_3.setObjectName("gun2TotalShotsLabel_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_3)
        self.tb2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb2TotalShotsSpinBox.setMaximum(10000000)
        self.tb2TotalShotsSpinBox.setObjectName("tb2TotalShotsSpinBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tb2TotalShotsSpinBox)
        self.gun3TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun3TotalShotsLabel_3.setObjectName("gun3TotalShotsLabel_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_3)
        self.tb3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb3TotalShotsSpinBox.setMaximum(10000000)
        self.tb3TotalShotsSpinBox.setObjectName("tb3TotalShotsSpinBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tb3TotalShotsSpinBox)
        self.gun4TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun4TotalShotsLabel_3.setObjectName("gun4TotalShotsLabel_3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_3)
        self.tb4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb4TotalShotsSpinBox.setMaximum(10000000)
        self.tb4TotalShotsSpinBox.setObjectName("tb4TotalShotsSpinBox")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tb4TotalShotsSpinBox)
        self.gun5TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun5TotalShotsLabel_3.setObjectName("gun5TotalShotsLabel_3")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_3)
        self.tb5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb5TotalShotsSpinBox.setMaximum(10000000)
        self.tb5TotalShotsSpinBox.setObjectName("tb5TotalShotsSpinBox")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tb5TotalShotsSpinBox)
        self.gun6TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun6TotalShotsLabel_3.setObjectName("gun6TotalShotsLabel_3")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_3)
        self.tb6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb6TotalShotsSpinBox.setMaximum(10000000)
        self.tb6TotalShotsSpinBox.setObjectName("tb6TotalShotsSpinBox")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tb6TotalShotsSpinBox)
        self.mSGTotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.mSGTotalShotsLabel_3.setObjectName("mSGTotalShotsLabel_3")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_3)
        self.msg_tb_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.msg_tb_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.msg_tb_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.msg_tb_TotalShotsSpinBox.setMaximum(10000000)
        self.msg_tb_TotalShotsSpinBox.setObjectName("msg_tb_TotalShotsSpinBox")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.msg_tb_TotalShotsSpinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_6.setObjectName("formLayout_6")
        self.gun1TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun1TotalShotsLabel_4.setObjectName("gun1TotalShotsLabel_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_4)
        self.sol1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sol1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.sol1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.sol1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol1TotalShotsSpinBox.setMaximum(10000000)
        self.sol1TotalShotsSpinBox.setObjectName("sol1TotalShotsSpinBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sol1TotalShotsSpinBox)
        self.gun2TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun2TotalShotsLabel_4.setObjectName("gun2TotalShotsLabel_4")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_4)
        self.sol2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol2TotalShotsSpinBox.setMaximum(10000000)
        self.sol2TotalShotsSpinBox.setObjectName("sol2TotalShotsSpinBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sol2TotalShotsSpinBox)
        self.gun3TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun3TotalShotsLabel_4.setObjectName("gun3TotalShotsLabel_4")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_4)
        self.sol3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol3TotalShotsSpinBox.setMaximum(10000000)
        self.sol3TotalShotsSpinBox.setObjectName("sol3TotalShotsSpinBox")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sol3TotalShotsSpinBox)
        self.gun4TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun4TotalShotsLabel_4.setObjectName("gun4TotalShotsLabel_4")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_4)
        self.sol4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol4TotalShotsSpinBox.setMaximum(10000000)
        self.sol4TotalShotsSpinBox.setObjectName("sol4TotalShotsSpinBox")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sol4TotalShotsSpinBox)
        self.gun5TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun5TotalShotsLabel_4.setObjectName("gun5TotalShotsLabel_4")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_4)
        self.sol5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol5TotalShotsSpinBox.setMaximum(10000000)
        self.sol5TotalShotsSpinBox.setObjectName("sol5TotalShotsSpinBox")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sol5TotalShotsSpinBox)
        self.gun6TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun6TotalShotsLabel_4.setObjectName("gun6TotalShotsLabel_4")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_4)
        self.sol6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol6TotalShotsSpinBox.setMaximum(10000000)
        self.sol6TotalShotsSpinBox.setObjectName("sol6TotalShotsSpinBox")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sol6TotalShotsSpinBox)
        self.mSGTotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.mSGTotalShotsLabel_4.setObjectName("mSGTotalShotsLabel_4")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_4)
        self.msg_sol_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.msg_sol_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.msg_sol_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.msg_sol_TotalShotsSpinBox.setMaximum(10000000)
        self.msg_sol_TotalShotsSpinBox.setObjectName("msg_sol_TotalShotsSpinBox")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.msg_sol_TotalShotsSpinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontal_buttons = QtWidgets.QHBoxLayout()
        self.horizontal_buttons.setObjectName("horizontal_buttons")
        self.copy_shots_btn = QtWidgets.QPushButton(self.groupBox)
        self.copy_shots_btn.setObjectName("copy_shots_btn")
        self.horizontal_buttons.addWidget(self.copy_shots_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_buttons.addItem(spacerItem)
        self.add_new_record_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_new_record_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.add_new_record_btn.setObjectName("add_new_record_btn")
        self.horizontal_buttons.addWidget(self.add_new_record_btn)
        self.verticalLayout_3.addLayout(self.horizontal_buttons)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.gun1ShotsFiredLabel = QtWidgets.QLabel(self.groupBox_7)
        self.gun1ShotsFiredLabel.setObjectName("gun1ShotsFiredLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1ShotsFiredLabel)
        self.gun1_counter_txt = QtWidgets.QLineEdit(self.groupBox_7)
        self.gun1_counter_txt.setObjectName("gun1_counter_txt")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gun1_counter_txt)
        self.gun2ShotsFiredLabel = QtWidgets.QLabel(self.groupBox_7)
        self.gun2ShotsFiredLabel.setObjectName("gun2ShotsFiredLabel")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gun2ShotsFiredLabel)
        self.gun2ShotsFiredLineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.gun2ShotsFiredLineEdit.setObjectName("gun2ShotsFiredLineEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gun2ShotsFiredLineEdit)
        self.gun3ShotsFiredLabel = QtWidgets.QLabel(self.groupBox_7)
        self.gun3ShotsFiredLabel.setObjectName("gun3ShotsFiredLabel")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun3ShotsFiredLabel)
        self.gun3ShotsFiredLineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.gun3ShotsFiredLineEdit.setObjectName("gun3ShotsFiredLineEdit")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gun3ShotsFiredLineEdit)
        self.gun4ShotsFiredLabel = QtWidgets.QLabel(self.groupBox_7)
        self.gun4ShotsFiredLabel.setObjectName("gun4ShotsFiredLabel")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun4ShotsFiredLabel)
        self.gun4ShotsFiredLineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.gun4ShotsFiredLineEdit.setObjectName("gun4ShotsFiredLineEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gun4ShotsFiredLineEdit)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 600))
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setHorizontalSpacing(50)
        self.formLayout_2.setObjectName("formLayout_2")
        self.recordIDLabel = QtWidgets.QLabel(self.groupBox_2)
        self.recordIDLabel.setObjectName("recordIDLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.recordIDLabel)
        self.recordIDLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.recordIDLineEdit.setEnabled(False)
        self.recordIDLineEdit.setClearButtonEnabled(False)
        self.recordIDLineEdit.setObjectName("recordIDLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recordIDLineEdit)
        self.gunNumberLabel = QtWidgets.QLabel(self.groupBox_2)
        self.gunNumberLabel.setObjectName("gunNumberLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gunNumberLabel)
        self.gunNumberLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gunNumberLineEdit.setEnabled(False)
        self.gunNumberLineEdit.setObjectName("gunNumberLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gunNumberLineEdit)
        self.dateLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dateLineEdit.setEnabled(False)
        self.dateLineEdit.setObjectName("dateLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateLineEdit)
        self.totalShotsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalShotsLabel.setObjectName("totalShotsLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.totalShotsLabel)
        self.totalShotsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.totalShotsLineEdit.setEnabled(False)
        self.totalShotsLineEdit.setObjectName("totalShotsLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.totalShotsLineEdit)
        self.totalAirlineShotsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalAirlineShotsLabel.setObjectName("totalAirlineShotsLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.totalAirlineShotsLabel)
        self.totalAirlineShotsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.totalAirlineShotsLineEdit.setEnabled(False)
        self.totalAirlineShotsLineEdit.setObjectName("totalAirlineShotsLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.totalAirlineShotsLineEdit)
        self.totalTBsShotsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalTBsShotsLabel.setObjectName("totalTBsShotsLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.totalTBsShotsLabel)
        self.totalTBsShotsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.totalTBsShotsLineEdit.setEnabled(False)
        self.totalTBsShotsLineEdit.setObjectName("totalTBsShotsLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.totalTBsShotsLineEdit)
        self.totalSolenoidShotsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalSolenoidShotsLabel.setObjectName("totalSolenoidShotsLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.totalSolenoidShotsLabel)
        self.totalSolenoidShotsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.totalSolenoidShotsLineEdit.setEnabled(False)
        self.totalSolenoidShotsLineEdit.setObjectName("totalSolenoidShotsLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.totalSolenoidShotsLineEdit)
        self.commentsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.commentsLabel.setObjectName("commentsLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.commentsLabel)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.airlineTypeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.airlineTypeLabel.setObjectName("airlineTypeLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.airlineTypeLabel)
        self.airlineTypeLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.airlineTypeLineEdit.setEnabled(False)
        self.airlineTypeLineEdit.setObjectName("airlineTypeLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.airlineTypeLineEdit)
        self.projectLabel = QtWidgets.QLabel(self.groupBox_2)
        self.projectLabel.setObjectName("projectLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.projectLabel)
        self.projectLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.projectLineEdit.setEnabled(False)
        self.projectLineEdit.setObjectName("projectLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.projectLineEdit)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.MplLineWidget = MplLineWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplLineWidget.sizePolicy().hasHeightForWidth())
        self.MplLineWidget.setSizePolicy(sizePolicy)
        self.MplLineWidget.setMinimumSize(QtCore.QSize(600, 150))
        self.MplLineWidget.setObjectName("MplLineWidget")
        self.verticalLayout_2.addWidget(self.MplLineWidget)
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1806, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Add new record"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Guns stats:"))
        self.dateAndTimeLabel.setText(_translate("MainWindow", "Date and time:"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project name:"))
        self.gun1TotalShotsLabel.setText(_translate("MainWindow", "Gun 1 Total Shots"))
        self.gun2TotalShotsLabel.setText(_translate("MainWindow", "Gun 2 Total Shots:"))
        self.gun3TotalShotsLabel.setText(_translate("MainWindow", "Gun 3 Total Shots:"))
        self.gun4TotalShotsLabel.setText(_translate("MainWindow", "Gun 4 Total Shots:"))
        self.gun5TotalShotsLabel.setText(_translate("MainWindow", "Gun 5 Total Shots:"))
        self.gun6TotalShotsLabel.setText(_translate("MainWindow", "Gun 6 Total Shots:"))
        self.mSGTotalShotsLabel.setText(_translate("MainWindow", "MSG Total Shots:"))
        self.commentsLabel_2.setText(_translate("MainWindow", "Comments:"))
        self.comments_txt.setPlaceholderText(_translate("MainWindow", "Enter comment here"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Airline stats"))
        self.gun1TotalShotsLabel_2.setText(_translate("MainWindow", "Airline 1 Total Shots:"))
        self.airline1TypeLabel.setText(_translate("MainWindow", "Airline 1 Type:"))
        self.gun2TotalShotsLabel_2.setText(_translate("MainWindow", "Airline 2 Total Shots:"))
        self.gun3TotalShotsLabel_2.setText(_translate("MainWindow", "Arileine 3 Total Shots:"))
        self.airline3TypeLabel.setText(_translate("MainWindow", "Airline 3 Type:"))
        self.gun4TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 4 Total Shots:"))
        self.airline4TypeLabel.setText(_translate("MainWindow", "Airline 4 Type:"))
        self.gun5TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 5 Total Shots:"))
        self.gun6TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 6 Total Shots:"))
        self.airline6TypeLabel.setText(_translate("MainWindow", "Airline 6 Type:"))
        self.mSGTotalShotsLabel_2.setText(_translate("MainWindow", "MSG Total Shots:"))
        self.airlineForMSGLabel.setText(_translate("MainWindow", "Airline for MSG:"))
        self.airline5TypeLabel.setText(_translate("MainWindow", "Airline 5 Type:"))
        self.airline2TypeLabel.setText(_translate("MainWindow", "Airline 2 Type:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "TBs stats:"))
        self.gun1TotalShotsLabel_3.setText(_translate("MainWindow", "TB 1 Total Shots"))
        self.gun2TotalShotsLabel_3.setText(_translate("MainWindow", "TB 2 Total Shots:"))
        self.gun3TotalShotsLabel_3.setText(_translate("MainWindow", "TB 3 Total Shots:"))
        self.gun4TotalShotsLabel_3.setText(_translate("MainWindow", "TB 4 Total Shots:"))
        self.gun5TotalShotsLabel_3.setText(_translate("MainWindow", "TB 5 Total Shots:"))
        self.gun6TotalShotsLabel_3.setText(_translate("MainWindow", "TB 6 Total Shots:"))
        self.mSGTotalShotsLabel_3.setText(_translate("MainWindow", "MSG TB Total Shots:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Solenoids stats:"))
        self.gun1TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 1 Total Shots"))
        self.gun2TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 2 Total Shots:"))
        self.gun3TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 3 Total Shots:"))
        self.gun4TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 4 Total Shots:"))
        self.gun5TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 5 Total Shots:"))
        self.gun6TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 6 Total Shots:"))
        self.mSGTotalShotsLabel_4.setText(_translate("MainWindow", "MSG Sol Total Shots:"))
        self.copy_shots_btn.setText(_translate("MainWindow", "Copy shots"))
        self.add_new_record_btn.setText(_translate("MainWindow", "Add new record"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Main information since last record"))
        self.gun1ShotsFiredLabel.setText(_translate("MainWindow", "Gun 1 shots fired:"))
        self.gun2ShotsFiredLabel.setText(_translate("MainWindow", "Gun 2 shots fired:"))
        self.gun3ShotsFiredLabel.setText(_translate("MainWindow", "Gun 3 shots fired:"))
        self.gun4ShotsFiredLabel.setText(_translate("MainWindow", "Gun 4 shots fired:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Information"))
        self.recordIDLabel.setText(_translate("MainWindow", "Record ID:"))
        self.gunNumberLabel.setText(_translate("MainWindow", "Gun number:"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.totalShotsLabel.setText(_translate("MainWindow", "Total shots:"))
        self.totalAirlineShotsLabel.setText(_translate("MainWindow", "Total Airline shots:"))
        self.totalTBsShotsLabel.setText(_translate("MainWindow", "Total TBs shots:"))
        self.totalSolenoidShotsLabel.setText(_translate("MainWindow", "Total Solenoid shots:"))
        self.commentsLabel.setText(_translate("MainWindow", "Comments:"))
        self.airlineTypeLabel.setText(_translate("MainWindow", "Airline type:"))
        self.projectLabel.setText(_translate("MainWindow", "Project:"))
from mpllinewidget import MplLineWidget
from mplwidget import MplWidget
