# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1905, 1204)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(315, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(315, 16777215))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.dateAndTimeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.dateAndTimeLabel.setObjectName("dateAndTimeLabel")
        self.gridLayout.addWidget(self.dateAndTimeLabel, 0, 0, 1, 1)
        self.gun2TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun2TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun2TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun2TotalShotsLabel.setObjectName("gun2TotalShotsLabel")
        self.gridLayout.addWidget(self.gun2TotalShotsLabel, 3, 0, 1, 1)
        self.gun3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun3TotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.gun3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun3TotalShotsSpinBox.setMaximum(10000000)
        self.gun3TotalShotsSpinBox.setObjectName("gun3TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun3TotalShotsSpinBox, 4, 1, 1, 1)
        self.gun5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun5TotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.gun5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun5TotalShotsSpinBox.setMaximum(10000000)
        self.gun5TotalShotsSpinBox.setObjectName("gun5TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun5TotalShotsSpinBox, 6, 1, 1, 1)
        self.projectNameLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.projectNameLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.projectNameLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.gridLayout.addWidget(self.projectNameLineEdit, 1, 1, 1, 1)
        self.gun3TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun3TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun3TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun3TotalShotsLabel.setObjectName("gun3TotalShotsLabel")
        self.gridLayout.addWidget(self.gun3TotalShotsLabel, 4, 0, 1, 1)
        self.mSGTotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSGTotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.mSGTotalShotsLabel.setSizePolicy(sizePolicy)
        self.mSGTotalShotsLabel.setObjectName("mSGTotalShotsLabel")
        self.gridLayout.addWidget(self.mSGTotalShotsLabel, 8, 0, 1, 1)
        self.gun1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.gun1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.gun1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun1TotalShotsSpinBox.setMaximum(10000000)
        self.gun1TotalShotsSpinBox.setObjectName("gun1TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun1TotalShotsSpinBox, 2, 1, 1, 1)
        self.gun6TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun6TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun6TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun6TotalShotsLabel.setObjectName("gun6TotalShotsLabel")
        self.gridLayout.addWidget(self.gun6TotalShotsLabel, 7, 0, 1, 1)
        self.dateAndTimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateAndTimeDateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateAndTimeDateTimeEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dateAndTimeDateTimeEdit.setDate(QtCore.QDate(2020, 6, 1))
        self.dateAndTimeDateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateAndTimeDateTimeEdit.setCalendarPopup(True)
        self.dateAndTimeDateTimeEdit.setObjectName("dateAndTimeDateTimeEdit")
        self.gridLayout.addWidget(self.dateAndTimeDateTimeEdit, 0, 1, 1, 1)
        self.projectNameLabel = QtWidgets.QLabel(self.groupBox_3)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.gridLayout.addWidget(self.projectNameLabel, 1, 0, 1, 1)
        self.gun2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun2TotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.gun2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun2TotalShotsSpinBox.setMaximum(10000000)
        self.gun2TotalShotsSpinBox.setObjectName("gun2TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun2TotalShotsSpinBox, 3, 1, 1, 1)
        self.gun4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun4TotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.gun4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun4TotalShotsSpinBox.setMaximum(10000000)
        self.gun4TotalShotsSpinBox.setObjectName("gun4TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun4TotalShotsSpinBox, 5, 1, 1, 1)
        self.gun6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.gun6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.gun6TotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.gun6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gun6TotalShotsSpinBox.setMaximum(10000000)
        self.gun6TotalShotsSpinBox.setObjectName("gun6TotalShotsSpinBox")
        self.gridLayout.addWidget(self.gun6TotalShotsSpinBox, 7, 1, 1, 1)
        self.commentsLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.commentsLabel_2.setObjectName("commentsLabel_2")
        self.gridLayout.addWidget(self.commentsLabel_2, 9, 0, 1, 1)
        self.gun5TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun5TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun5TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun5TotalShotsLabel.setObjectName("gun5TotalShotsLabel")
        self.gridLayout.addWidget(self.gun5TotalShotsLabel, 6, 0, 1, 1)
        self.gun1TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun1TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun1TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun1TotalShotsLabel.setObjectName("gun1TotalShotsLabel")
        self.gridLayout.addWidget(self.gun1TotalShotsLabel, 2, 0, 1, 1)
        self.comments_txt = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments_txt.sizePolicy().hasHeightForWidth())
        self.comments_txt.setSizePolicy(sizePolicy)
        self.comments_txt.setMinimumSize(QtCore.QSize(200, 100))
        self.comments_txt.setMaximumSize(QtCore.QSize(200, 100))
        self.comments_txt.setUndoRedoEnabled(True)
        self.comments_txt.setReadOnly(False)
        self.comments_txt.setObjectName("comments_txt")
        self.gridLayout.addWidget(self.comments_txt, 9, 1, 1, 1)
        self.gun4TotalShotsLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gun4TotalShotsLabel.sizePolicy().hasHeightForWidth())
        self.gun4TotalShotsLabel.setSizePolicy(sizePolicy)
        self.gun4TotalShotsLabel.setObjectName("gun4TotalShotsLabel")
        self.gridLayout.addWidget(self.gun4TotalShotsLabel, 5, 0, 1, 1)
        self.mSGTotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.mSGTotalShotsSpinBox.setMinimumSize(QtCore.QSize(90, 0))
        self.mSGTotalShotsSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.mSGTotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mSGTotalShotsSpinBox.setMaximum(10000000)
        self.mSGTotalShotsSpinBox.setObjectName("mSGTotalShotsSpinBox")
        self.gridLayout.addWidget(self.mSGTotalShotsSpinBox, 8, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 3, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 4, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 5, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 6, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout.addWidget(self.comboBox_6, 7, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 8, 2, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setObjectName("formLayout_4")
        self.gun1TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun1TotalShotsLabel_2.setObjectName("gun1TotalShotsLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_2)
        self.airline1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airline1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.airline1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.airline1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline1TotalShotsSpinBox.setMaximum(10000000)
        self.airline1TotalShotsSpinBox.setObjectName("airline1TotalShotsSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.airline1TotalShotsSpinBox)
        self.airline1TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline1TypeLabel.setObjectName("airline1TypeLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.airline1TypeLabel)
        self.airline1TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline1TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline1TypeComboBox.setObjectName("airline1TypeComboBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.airline1TypeComboBox)
        self.gun2TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun2TotalShotsLabel_2.setObjectName("gun2TotalShotsLabel_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_2)
        self.airline2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline2TotalShotsSpinBox.setMaximum(10000000)
        self.airline2TotalShotsSpinBox.setObjectName("airline2TotalShotsSpinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.airline2TotalShotsSpinBox)
        self.airline2TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline2TypeLabel.setObjectName("airline2TypeLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.airline2TypeLabel)
        self.airline2TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline2TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline2TypeComboBox.setObjectName("airline2TypeComboBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.airline2TypeComboBox)
        self.gun3TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun3TotalShotsLabel_2.setObjectName("gun3TotalShotsLabel_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_2)
        self.airline3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline3TotalShotsSpinBox.setMaximum(10000000)
        self.airline3TotalShotsSpinBox.setObjectName("airline3TotalShotsSpinBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.airline3TotalShotsSpinBox)
        self.airline3TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline3TypeLabel.setObjectName("airline3TypeLabel")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.airline3TypeLabel)
        self.airline3TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline3TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline3TypeComboBox.setObjectName("airline3TypeComboBox")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.airline3TypeComboBox)
        self.gun4TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun4TotalShotsLabel_2.setObjectName("gun4TotalShotsLabel_2")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_2)
        self.airline4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline4TotalShotsSpinBox.setMaximum(10000000)
        self.airline4TotalShotsSpinBox.setObjectName("airline4TotalShotsSpinBox")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.airline4TotalShotsSpinBox)
        self.airline4TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline4TypeLabel.setObjectName("airline4TypeLabel")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.airline4TypeLabel)
        self.airline4TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline4TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline4TypeComboBox.setObjectName("airline4TypeComboBox")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.airline4TypeComboBox)
        self.gun5TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun5TotalShotsLabel_2.setObjectName("gun5TotalShotsLabel_2")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_2)
        self.airline5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline5TotalShotsSpinBox.setMaximum(10000000)
        self.airline5TotalShotsSpinBox.setObjectName("airline5TotalShotsSpinBox")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.airline5TotalShotsSpinBox)
        self.airline5TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline5TypeLabel.setObjectName("airline5TypeLabel")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.airline5TypeLabel)
        self.airline5TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline5TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline5TypeComboBox.setObjectName("airline5TypeComboBox")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.airline5TypeComboBox)
        self.gun6TotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.gun6TotalShotsLabel_2.setObjectName("gun6TotalShotsLabel_2")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_2)
        self.airline6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.airline6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.airline6TotalShotsSpinBox.setMaximum(10000000)
        self.airline6TotalShotsSpinBox.setObjectName("airline6TotalShotsSpinBox")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.airline6TotalShotsSpinBox)
        self.airline6TypeLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airline6TypeLabel.setObjectName("airline6TypeLabel")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.airline6TypeLabel)
        self.airline6TypeComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airline6TypeComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airline6TypeComboBox.setObjectName("airline6TypeComboBox")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.airline6TypeComboBox)
        self.mSGTotalShotsLabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.mSGTotalShotsLabel_2.setObjectName("mSGTotalShotsLabel_2")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_2)
        self.mSG_airline_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.mSG_airline_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.mSG_airline_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mSG_airline_TotalShotsSpinBox.setMaximum(10000000)
        self.mSG_airline_TotalShotsSpinBox.setObjectName("mSG_airline_TotalShotsSpinBox")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.mSG_airline_TotalShotsSpinBox)
        self.airlineForMSGLabel = QtWidgets.QLabel(self.groupBox_4)
        self.airlineForMSGLabel.setObjectName("airlineForMSGLabel")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.airlineForMSGLabel)
        self.airlineForMSGComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.airlineForMSGComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.airlineForMSGComboBox.setObjectName("airlineForMSGComboBox")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.airlineForMSGComboBox)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_5.setObjectName("formLayout_5")
        self.gun1TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun1TotalShotsLabel_3.setObjectName("gun1TotalShotsLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_3)
        self.tb1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.tb1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.tb1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb1TotalShotsSpinBox.setMaximum(10000000)
        self.tb1TotalShotsSpinBox.setObjectName("tb1TotalShotsSpinBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tb1TotalShotsSpinBox)
        self.gun2TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun2TotalShotsLabel_3.setObjectName("gun2TotalShotsLabel_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_3)
        self.tb2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb2TotalShotsSpinBox.setMaximum(10000000)
        self.tb2TotalShotsSpinBox.setObjectName("tb2TotalShotsSpinBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tb2TotalShotsSpinBox)
        self.gun3TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun3TotalShotsLabel_3.setObjectName("gun3TotalShotsLabel_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_3)
        self.tb3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb3TotalShotsSpinBox.setMaximum(10000000)
        self.tb3TotalShotsSpinBox.setObjectName("tb3TotalShotsSpinBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tb3TotalShotsSpinBox)
        self.gun4TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun4TotalShotsLabel_3.setObjectName("gun4TotalShotsLabel_3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_3)
        self.tb4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb4TotalShotsSpinBox.setMaximum(10000000)
        self.tb4TotalShotsSpinBox.setObjectName("tb4TotalShotsSpinBox")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tb4TotalShotsSpinBox)
        self.gun5TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun5TotalShotsLabel_3.setObjectName("gun5TotalShotsLabel_3")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_3)
        self.tb5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb5TotalShotsSpinBox.setMaximum(10000000)
        self.tb5TotalShotsSpinBox.setObjectName("tb5TotalShotsSpinBox")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tb5TotalShotsSpinBox)
        self.gun6TotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.gun6TotalShotsLabel_3.setObjectName("gun6TotalShotsLabel_3")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_3)
        self.tb6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.tb6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tb6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb6TotalShotsSpinBox.setMaximum(10000000)
        self.tb6TotalShotsSpinBox.setObjectName("tb6TotalShotsSpinBox")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tb6TotalShotsSpinBox)
        self.mSGTotalShotsLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.mSGTotalShotsLabel_3.setObjectName("mSGTotalShotsLabel_3")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_3)
        self.msg_tb_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.msg_tb_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.msg_tb_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.msg_tb_TotalShotsSpinBox.setMaximum(10000000)
        self.msg_tb_TotalShotsSpinBox.setObjectName("msg_tb_TotalShotsSpinBox")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.msg_tb_TotalShotsSpinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_6.setObjectName("formLayout_6")
        self.gun1TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun1TotalShotsLabel_4.setObjectName("gun1TotalShotsLabel_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gun1TotalShotsLabel_4)
        self.sol1TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sol1TotalShotsSpinBox.sizePolicy().hasHeightForWidth())
        self.sol1TotalShotsSpinBox.setSizePolicy(sizePolicy)
        self.sol1TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol1TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol1TotalShotsSpinBox.setMaximum(10000000)
        self.sol1TotalShotsSpinBox.setObjectName("sol1TotalShotsSpinBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sol1TotalShotsSpinBox)
        self.gun2TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun2TotalShotsLabel_4.setObjectName("gun2TotalShotsLabel_4")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gun2TotalShotsLabel_4)
        self.sol2TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol2TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol2TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol2TotalShotsSpinBox.setMaximum(10000000)
        self.sol2TotalShotsSpinBox.setObjectName("sol2TotalShotsSpinBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sol2TotalShotsSpinBox)
        self.gun3TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun3TotalShotsLabel_4.setObjectName("gun3TotalShotsLabel_4")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gun3TotalShotsLabel_4)
        self.sol3TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol3TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol3TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol3TotalShotsSpinBox.setMaximum(10000000)
        self.sol3TotalShotsSpinBox.setObjectName("sol3TotalShotsSpinBox")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sol3TotalShotsSpinBox)
        self.gun4TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun4TotalShotsLabel_4.setObjectName("gun4TotalShotsLabel_4")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gun4TotalShotsLabel_4)
        self.sol4TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol4TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol4TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol4TotalShotsSpinBox.setMaximum(10000000)
        self.sol4TotalShotsSpinBox.setObjectName("sol4TotalShotsSpinBox")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sol4TotalShotsSpinBox)
        self.gun5TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun5TotalShotsLabel_4.setObjectName("gun5TotalShotsLabel_4")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gun5TotalShotsLabel_4)
        self.sol5TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol5TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol5TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol5TotalShotsSpinBox.setMaximum(10000000)
        self.sol5TotalShotsSpinBox.setObjectName("sol5TotalShotsSpinBox")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sol5TotalShotsSpinBox)
        self.gun6TotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.gun6TotalShotsLabel_4.setObjectName("gun6TotalShotsLabel_4")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gun6TotalShotsLabel_4)
        self.sol6TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sol6TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sol6TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sol6TotalShotsSpinBox.setMaximum(10000000)
        self.sol6TotalShotsSpinBox.setObjectName("sol6TotalShotsSpinBox")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sol6TotalShotsSpinBox)
        self.mSGTotalShotsLabel_4 = QtWidgets.QLabel(self.groupBox_6)
        self.mSGTotalShotsLabel_4.setObjectName("mSGTotalShotsLabel_4")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mSGTotalShotsLabel_4)
        self.msg_sol_TotalShotsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.msg_sol_TotalShotsSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.msg_sol_TotalShotsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.msg_sol_TotalShotsSpinBox.setMaximum(10000000)
        self.msg_sol_TotalShotsSpinBox.setObjectName("msg_sol_TotalShotsSpinBox")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.msg_sol_TotalShotsSpinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.MplLineWidget = MplLineWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplLineWidget.sizePolicy().hasHeightForWidth())
        self.MplLineWidget.setSizePolicy(sizePolicy)
        self.MplLineWidget.setMinimumSize(QtCore.QSize(600, 150))
        self.MplLineWidget.setObjectName("MplLineWidget")
        self.horizontalLayout_4.addWidget(self.MplLineWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontal_buttons = QtWidgets.QHBoxLayout()
        self.horizontal_buttons.setObjectName("horizontal_buttons")
        self.copy_shots_btn = QtWidgets.QPushButton(self.groupBox)
        self.copy_shots_btn.setObjectName("copy_shots_btn")
        self.horizontal_buttons.addWidget(self.copy_shots_btn)
        self.add_new_record_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_new_record_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.add_new_record_btn.setObjectName("add_new_record_btn")
        self.horizontal_buttons.addWidget(self.add_new_record_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_buttons.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontal_buttons)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1905, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Detailed information:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Guns stats:"))
        self.dateAndTimeLabel.setText(_translate("MainWindow", "Date and time:"))
        self.gun2TotalShotsLabel.setText(_translate("MainWindow", "Gun 2:"))
        self.gun3TotalShotsLabel.setText(_translate("MainWindow", "Gun 3:"))
        self.mSGTotalShotsLabel.setText(_translate("MainWindow", "MSG:"))
        self.gun6TotalShotsLabel.setText(_translate("MainWindow", "Gun 6:"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project name:"))
        self.commentsLabel_2.setText(_translate("MainWindow", "Comments:"))
        self.gun5TotalShotsLabel.setText(_translate("MainWindow", "Gun 5:"))
        self.gun1TotalShotsLabel.setText(_translate("MainWindow", "Gun 1:"))
        self.comments_txt.setPlaceholderText(_translate("MainWindow", "Enter comment here"))
        self.gun4TotalShotsLabel.setText(_translate("MainWindow", "Gun 4:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Airline stats"))
        self.gun1TotalShotsLabel_2.setText(_translate("MainWindow", "Airline 1 Total Shots:"))
        self.airline1TypeLabel.setText(_translate("MainWindow", "Airline 1 Type:"))
        self.gun2TotalShotsLabel_2.setText(_translate("MainWindow", "Airline 2 Total Shots:"))
        self.airline2TypeLabel.setText(_translate("MainWindow", "Airline 2 Type:"))
        self.gun3TotalShotsLabel_2.setText(_translate("MainWindow", "Arileine 3 Total Shots:"))
        self.airline3TypeLabel.setText(_translate("MainWindow", "Airline 3 Type:"))
        self.gun4TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 4 Total Shots:"))
        self.airline4TypeLabel.setText(_translate("MainWindow", "Airline 4 Type:"))
        self.gun5TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 5 Total Shots:"))
        self.airline5TypeLabel.setText(_translate("MainWindow", "Airline 5 Type:"))
        self.gun6TotalShotsLabel_2.setText(_translate("MainWindow", "Gun 6 Total Shots:"))
        self.airline6TypeLabel.setText(_translate("MainWindow", "Airline 6 Type:"))
        self.mSGTotalShotsLabel_2.setText(_translate("MainWindow", "MSG Total Shots:"))
        self.airlineForMSGLabel.setText(_translate("MainWindow", "Airline for MSG:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "TBs stats:"))
        self.gun1TotalShotsLabel_3.setText(_translate("MainWindow", "TB 1 Total Shots"))
        self.gun2TotalShotsLabel_3.setText(_translate("MainWindow", "TB 2 Total Shots:"))
        self.gun3TotalShotsLabel_3.setText(_translate("MainWindow", "TB 3 Total Shots:"))
        self.gun4TotalShotsLabel_3.setText(_translate("MainWindow", "TB 4 Total Shots:"))
        self.gun5TotalShotsLabel_3.setText(_translate("MainWindow", "TB 5 Total Shots:"))
        self.gun6TotalShotsLabel_3.setText(_translate("MainWindow", "TB 6 Total Shots:"))
        self.mSGTotalShotsLabel_3.setText(_translate("MainWindow", "MSG TB Total Shots:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Solenoids stats:"))
        self.gun1TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 1 Total Shots"))
        self.gun2TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 2 Total Shots:"))
        self.gun3TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 3 Total Shots:"))
        self.gun4TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 4 Total Shots:"))
        self.gun5TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 5 Total Shots:"))
        self.gun6TotalShotsLabel_4.setText(_translate("MainWindow", "Sol 6 Total Shots:"))
        self.mSGTotalShotsLabel_4.setText(_translate("MainWindow", "MSG Sol Total Shots:"))
        self.copy_shots_btn.setText(_translate("MainWindow", "Copy shots"))
        self.add_new_record_btn.setText(_translate("MainWindow", "Add new record"))
from mpllinewidget import MplLineWidget
from mplwidget import MplWidget
